export const MENUS = [
  {
    key: 'Clients',
    name: 'Clientes',
    icon: 'Briefcase',
    children: [
      {
        permission: 'module-clients',
        name: 'Vinculación de clientes',
        identifier: 'ClientsList',
        path: '/clientes',
      },
    ],
  },
  {
    key: 'ThirdParties',
    name: 'Terceros',
    icon: 'Users',
    children: [
      {
        permission: 'module-third-party',
        name: 'Vinculación de terceros',
        identifier: 'ThirdPartiesList',
        path: '/terceros',
      },
      {
        permission: 'module-third-party',
        name: 'Consulta de fideicomiso',
        identifier: 'TrustList',
        path: '/terceros/fideicomiso',
      },
    ],
  },
  {
    key: 'Users',
    name: 'Usuarios',
    icon: 'UserCog',
    children: [
      {
        permission: 'module-users',
        name: 'Gestión de usuarios',
        identifier: 'ListUserView',
        path: '/usuarios',
      },
      {
        permission: 'module-role',
        name: 'Roles',
        identifier: 'ListRoles',
        path: '/roles',
      },
      {
        permission: 'module-users-parameters',
        name: 'Parámetros',
        identifier: 'UserParametersList',
        path: '/parametros-usuario',
      },
    ],
  },
  {
    key: 'Treasury',
    name: 'Tesorería',
    icon: 'Wallet',
    children: [
      {
        permission: 'module-treasury',
        name: 'Traslados',
        identifier: 'BankTransferFilters',
        path: '/traslados-bancarios',
      },
      {
        permission: 'module-treasury',
        name: 'Tipos de recaudo',
        identifier: 'TypesCollectionList',
        path: '/tipos-recaudo',
      },
      {
        permission: 'module-checkbooks',
        name: 'Chequeras',
        identifier: 'CheckbooksList',
        path: '/tesoreria/chequeras',
      },
      {
        permission: 'module-treasury',
        name: 'Códigos de movimiento tesorería',
        identifier: 'TreasuryMovementCodesList',
        path: '/tesoreria/codigos-movimiento-tesoreria',
      },
      {
        permission: 'module-treasury',
        name: 'Equivalencias estructuras bancos',
        identifier: 'BankStructureEquivalencesList',
        path: '/tesoreria/equivalencias-estructuras-bancos',
      },
      {
        permission: 'module-accounting-blocks',
        name: 'Bloques contables',
        identifier: 'AccountingBlocksList',
        path: '/tesoreria/bloques-contables',
      },
      {
        permission: 'module-cancellation-code',
        name: 'Códigos de anulación',
        identifier: 'CancellationCodesList',
        path: '/tesoreria/codigos-anulacion-tesoreria',
      },
      {
        permission: 'module-payment-methods',
        name: 'Formas de pago',
        identifier: 'PaymentMethodsList',
        path: '/tesoreria/metodos-pago-tesoreria',
      },
      {
        permission: 'module-grounds-bank-refund',
        name: 'Causales de devolución bancaria',
        identifier: 'GroundsForBankRefund',
        path: '/tesoreria/causales-devolucion-bancaria',
      },
      {
        permission: 'module-banking-entities',
        name: 'Entidades bancarias',
        identifier: 'BankingEntitiesList',
        path: '/tesoreria/entidades-bancarias',
      },
      {
        permission: 'module-treasury',
        name: 'Cuentas bancarias',
        identifier: 'BankingAccountsList',
        path: '/tesoreria/cuentas-bancarias',
      },
      {
        permission: 'module-bank-account-balances',
        name: 'Saldos iniciales de cuentas bancarias',
        identifier: 'BankAccountBalancesList',
        path: '/tesoreria/saldos-iniciales-cuentas',
      },
      {
        permission: 'module-treasury',
        name: 'Estructuras flujo caja',
        identifier: 'CashFlowStructuresList',
        path: '/tesoreria/estructuras-flujo-caja',
      },
      {
        permission: 'module-collection-accounting-blocks',
        name: 'Bloques contables de recaudo',
        identifier: 'CollectionAccountingBlocksList',
        path: '/tesoreria/bloques-contables-recaudo',
      },
      {
        permission: 'module-treasury',
        name: 'Estructuras bancarias',
        identifier: 'BankStructuresList',
        path: '/tesoreria/estructuras-bancarias',
      },
      {
        permission: 'module-record-individual-expenses',
        name: 'Egresos individuales',
        identifier: 'RecordIndividualExpensesList',
        path: '/tesoreria/registrar-egresos-individuales',
      },
      {
        permission: 'module-treasury',
        name: 'Tipos de papel',
        identifier: 'PaperTypesList',
        path: '/tesoreria/tipos-papel',
      },
      {
        permission: 'module-cancel-bank-loads',
        name: 'Anulaciones Cargue Bancos',
        identifier: 'CancelLoadBanksList',
        path: '/tesoreria/anulaciones-cargue-bancos',
      },
      {
        permission: 'module-treasury',
        name: 'Autorizaciones de tesorería',
        identifier: 'AuthorizationTreasuryList',
        path: '/tesoreria/autorizaciones-tesoreria',
      },
      {
        permission: 'module-letter-formats',
        name: 'Formato de cartas',
        identifier: 'ListLetterFormatList',
        path: '/tesoreria/formato-carta-listado',
      },
      {
        permission: 'consecutive-vouchers',
        name: 'Consecutivos de comprobantes',
        identifier: 'ConsecutiveVouchersList',
        path: '/tesoreria/consecutivos-comprobantes',
      },
      {
        permission: 'module-treasury',
        name: 'Generar cartas grupo de dispersión',
        identifier: 'GenerateDispersionGroupLetterList',
        path: '/tesoreria/generar-cartas-grupo-dispersion',
      },
      {
        name: 'Autorización remota tesorería',
        identifier: 'RemoteAuthorizationList',
        path: '/tesoreria/autorizacion-remota-tesoreria',
      },
      {
        permission: 'consecutive-vouchers',
        name: 'Cheques con egreso',
        identifier: 'ExpenseChecksList',
        path: '/tesoreria/cheques-con-egreso',
      },
      {
        permission: 'consecutive-vouchers',
        name: 'Reimprimir cheques con egreso',
        identifier: 'ExpenseReprintChecksList',
        path: '/tesoreria/reimprimir-cheque-con-egreso',
      },
      {
        permission: 'module-cancel-bank-loads',
        name: 'Anulaciones Cargue Bancos',
        identifier: 'CancelLoadBanksList',
        path: '/tesoreria/anulaciones-cargue-bancos',
      },
    ],
  },
  {
    key: 'Security',
    name: 'Seguridad',
    icon: 'Shield',
    children: [
      {
        permission: 'module-security',
        name: 'Control de versión de módulos',
        identifier: 'VersionControl',
        path: '/seguridad/control-version-modulos',
      },
      {
        permission: 'module-security',
        name: 'Estado de usuarios',
        identifier: 'UserStatus',
        path: '/seguridad/estado-usuarios',
      },
      {
        permission: 'module-security',
        name: 'Horario de ingreso de usuarios',
        identifier: 'CheckinTime',
        path: '/seguridad/horario-ingreso-usuarios',
      },
      {
        permission: 'module-security',
        name: 'Intentos fallidos de ingreso',
        identifier: 'FailedAttemptsList',
        path: '/seguridad/intentos-fallidos',
      },
      {
        permission: 'module-security',
        name: 'Usuarios conectados',
        identifier: 'UserConnectedList',
        path: '/seguridad/usuarios-conectados',
      },
      {
        permission: 'module-security',
        name: 'Tiempo de conexión usuarios',
        identifier: 'ConnectionTime',
        path: '/seguridad/usuarios-conectados',
      },
    ],
  },
  {
    key: 'FICS',
    name: 'Fondo de inversión colectiva (FICS)',
    icon: 'PiggyBank',
    children: [
      {
        permission: '',
        name: 'Líneas de negocios y tipos de participación',
        identifier: 'BusinessLineList',
        path: '/fics/lineas-de-negocio-y-tipos-de-participacion',
      },
      {
        permission: '',
        name: 'Clases de movimiento',
        identifier: 'SettingMovementClassesList',
        path: '/fics/lineas-de-movimiento',
      },
      {
        permission: 'module-fics',
        name: 'Código de movimiento',
        identifier: 'MovementCodesList',
        path: '/fics/codigos-movimiento',
      },
      {
        permission: 'collective-investment-fund',
        name: 'Tipo de fondos y de operación',
        identifier: 'CollectiveInvestmentFundList',
        path: '/fics/tipos-fondos-y-operacion',
      },
      {
        permission: 'participation-type-registration',
        name: 'Registro tipo de participación',
        identifier: 'ParticipationTypeRegistrationList',
        path: '/participation-type-registration',
      },
      {
        permission: 'module-fics',
        name: 'Causales de rechazo de operación',
        identifier: 'OperationRejectionReasonsList',
        path: '/fics/causales-rechazo-operacion',
      },
      {
        permission: 'module-fics',
        name: 'Planes de inversión fiduciaria',
        identifier: 'OperationRejectionReasonsList',
        path: '/fics/causales-rechazo-operacion',
      },
      {
        permission: 'module-fics-consolidated-investment',
        name: 'Creación fondo de inversión consolidador y asignación compartimentos',
        identifier: 'ConsolidatedInvestmentList',
        path: '/fics/consolidador-compartimientos',
      },
      {
        permission: 'module-fics',
        name: 'Planes de inversión fiduciaria',
        identifier: 'OperationRejectionReasonsList',
        path: '/fics/causales-rechazo-operacion',
      },
      {
        permission: 'module-fics',
        name: 'Registro de operaciones para Aportes/Retiros',
        identifier: 'InvestmentPlanOperationList',
        path: '/fics/operaciones-plan-inversion',
      },
      {
        permission: 'module-fics',
        name: 'Validación cierre de fondos de inversión colectiva',
        identifier: 'ValidationFicsClosingList',
        path: '/fics/validacion-cierre-de-fondos-inversion-colectiva',
      },
    ],
  },
  {
    key: 'TrustBusiness',
    name: 'Negocios fiduciarios',
    icon: 'Handshake',
    children: [
      {
        permission: 'module-trust-business',
        name: 'Gestionar negocios fiduciarios',
        identifier: 'TrustBusinessesList',
        path: '/negocios-fiduciarios/negocios',
      },
      {
        permission: 'module-trust-business',
        name: 'Obligaciones financieras',
        identifier: 'FinancialObligationList',
        path: '/negocios-fiduciarios/obligaciones-financieras',
      },
      {
        permission: 'module-trust-business',
        name: 'Tablas de amortización',
        identifier: 'AmortizationTablesList',
        path: '/negocios-fiduciarios/tablas-de-amortizacion',
      },
      {
        permission: 'module-trust-business',
        name: 'Cambio de estado fideicomisos',
        identifier: 'ChangeTrustStatusList',
        path: '/negocios-fiduciarios/cambio-estado-fideicomisos',
      },
      {
        permission: 'module-trust-business',
        name: 'Prórroga fideicomiso',
        identifier: 'ExtendTrustList',
        path: '/negocios-fiduciarios/prorroga-fideicomiso',
      },
      {
        permission: 'module-trust-business',
        name: 'Código de movimiento de negocio',
        identifier: 'TrustBusinessMovementCodesList',
        path: '/negocios-fiduciarios/codigos-movimiento',
      },
      {
        permission: 'module-trust-business',
        name: 'Gestionar permisos por usuario',
        identifier: 'UserPermissionsList',
        path: '/negocios-fiduciarios/permisos/usuario',
      },
      {
        permission: 'module-trust-business',
        name: 'Gestionar permisos por negocio',
        identifier: 'BusinessPermissionsList',
        path: '/negocios-fiduciarios/permisos/negocio',
      },
      {
        permission: 'module-trust-business',
        name: 'Transferir permisos de usuario',
        identifier: 'UserPermissionsTransferList',
        path: '/negocios-fiduciarios/permisos/usuario/transferir',
      },
      {
        permission: 'module-guarantees',
        name: 'Garantías',
        identifier: 'GuaranteesList',
        path: '/negocios-fiduciarios/garantías',
      },
      {
        permission: 'module-fiduciary-trust',
        name: 'Encargos fiduciarios',
        identifier: 'FiduciaryTrustList',
        path: '/negocios-fiduciarios/encargos-fiduciarios',
      },
      {
        permission: 'module-fiduciary-trust',
        name: 'Plan de pagos',
        identifier: 'PaymentPlanList',
        path: '/negocios-fiduciarios/plan-de-pagos',
      },
    ],
  },
  {
    key: 'CalendarNotifications',
    name: 'Agenda y notificaciones',
    icon: 'CalendarCog',
    children: [
      {
        permission: 'module-calendar',
        name: 'Configurar calendario',
        identifier: 'ConfigCalendarList',
        path: '/calendario',
      },
      {
        permission: 'module-calendar-events',
        name: 'Configurar agenda',
        identifier: 'CalendarEventList',
        path: '/agenda',
      },
    ],
  },
  {
    key: 'InvestmentPortfolio',
    name: 'Portafolio de inversiones',
    icon: 'HandCoins',
    children: [
      {
        permission: '',
        name: 'Portafolio de inversión',
        identifier: 'InvestmentPortfolioList',
        path: '/portafolio-de-inversion',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Tipos de operaciones',
        identifier: 'TypesOperationList',
        path: '/portafolio-de-inversion/tipos-operaciones',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Definición cupos y permisos trader',
        identifier: 'TradePermitQuotaList',
        path: '/portafolio-de-inversion/definicion-cupos-y-permisos-trader',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Generar papeleta',
        identifier: 'GenerateBallotMenu',
        path: '/portafolio-de-inversion/generar-papeleta',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Tipos de bursatilidad',
        identifier: 'TypesMarketabilityList',
        path: '/portafolio-de-inversion/tipos-bursatilidad',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Tabla títulos amortizables',
        identifier: 'AmortizationTitleTableList',
        path: '/portafolio-de-inversion/tablas-de-amortizacion',
      },
      {
        permission: '',
        name: 'Calificaciones',
        identifier: 'QualificationsList',
        path: '/portafolio-de-inversiones/calificaciones',
      },
      {
        permission: 'currency',
        name: 'Crear moneda',
        identifier: 'CurrencyList',
        path: '/monedas',
      },
      {
        permission: '',
        name: 'Tasas de interés',
        identifier: 'InterestRatesList',
        path: '/tasas-de-interes',
      },
      {
        permission: '',
        name: 'Archivo proveedores precios',
        identifier: 'PriceProviderFile',
        path: '/portafolio-de-inversiones/archivo-proveedores-precios',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Registro ventas de renta variable acciones moneda local',
        identifier: 'RegisterSalesVariableIncomeShareLocalCurrencyCreate',
        path: '/portafolio-de-inversiones/registro-ventas-renta-variable-acciones-moneda-local/crear',
      },
      {
        permission: 'module-operational-etf',
        name: 'Operaciones de mercado',
        identifier: 'OperationalETFList',
        path: '/portafolio-de-inversiones/etf-operacionales',
      },
      {
        permission: 'module-fics-local-currency',
        name: 'Registro retiro participantes en FIC´s',
        identifier: 'LocalCurrencyWithdrawalCreate',
        path: '/portafolio-de-inversiones/registro-participacion-moneda-local/crear',
      },
      {
        permission: 'module-fics-foreign-currency',
        name: 'Registro retiro participantes en FIC´s moneda extranjera',
        identifier: 'ForeignCurrencyWithdrawalCreate',
        path: '/portafolio-de-inversiones/registro-participacion-moneda-extranjera/crear',
      },
      {
        permission: 'module-fics-local-currency',
        name: 'Registro retiro participantes en FIC´s',
        identifier: 'LocalCurrencyWithdrawalCreate',
        path: '/portafolio-de-inversiones/registro-participacion-moneda-local/crear',
      },
      {
        permission: 'module-fics-foreign-currency',
        name: 'Registro retiro participantes en FIC´s moneda extranjera',
        identifier: 'ForeignCurrencyWithdrawalCreate',
        path: '/portafolio-de-inversiones/registro-participacion-moneda-extranjera/crear',
      },
      {
        permission: 'module-register-monetary-market',
        name: 'Operaciones renta fija',
        identifier: 'RegisterMonetaryMarketList',
        path: '/portafolio-de-inversion/operaciones-renta-fija',
      },
      {
        permission: 'module-investment-portfolio',
        name: 'Englobes de títulos',
        identifier: 'TitlesMergingList',
        path: '/portafolio-de-inversiones/englobe-de-titulos',
      },
      {
        permission: 'module-foreign-exchange-sales-buy-operations',
        name: 'Divisas',
        identifier: 'ForeignExchangeSalesList',
        path: '/portafolio-de-inversiones/renta-variable',
      },
    ],
  },
  {
    key: 'Contability',
    name: 'Contabilidad',
    icon: 'FileText',
    children: [
      {
        permission: 'module-chart-account',
        name: 'Estructuras de cuentas',
        identifier: 'AccountStructureList',
        path: '/contabilidad/estructuras-de-cuentas',
      },
      {
        permission: 'module-account-balances',
        name: 'Validación de comprobantes',
        identifier: 'ValidationVoucherList',
        path: '/validacion-de-comprobantes',
      },
      {
        permission: 'module-account-balances',
        name: 'Consulta de saldos cuenta y terceros',
        identifier: 'AccountBalancesAndThirdPartiesList',
        path: '/contabilidad/consulta-de-saldos-cuenta-y-terceros',
      },
      {
        permission: 'module-query-movement-accounts',
        name: 'Consulta de movimientos por cuenta',
        identifier: 'QueryMovementAccountsList',
        path: '/consulta-movimientos-cuentas',
      },
      {
        permission: 'module-chart-account',
        name: 'Plan de cuentas',
        identifier: 'ChartAccountsList',
        path: '/plan-de-cuentas',
      },
      {
        permission: 'module-cost-center',
        name: 'Centro de costos',
        identifier: 'CostCenterList',
        path: '/centro-de-costos',
      },
      {
        permission: 'module-accounting-period-closing-parameters',
        name: 'Parámetros cierre de periodo',
        identifier: 'PeriodClosureParameterList',
        path: '/parametros-cierre-periodo',
      },
      {
        permission: 'module-period-closure',
        name: 'cierre de periodo',
        identifier: 'PeriodClosureList',
        path: '/cierre-periodo',
      },
      {
        permission: 'type-accounting-receipt',
        name: 'Tipos de comprobantes',
        identifier: 'TypeAccountingReceiptList',
        path: '/tipos-comprobantes-contables',
      },
      {
        permission: 'module-accounting-vouchers',
        name: 'Comprobantes contables',
        identifier: 'AccountingReceiptList',
        path: '/comprobantes-contables',
      },
      {
        permission: 'module-accounting-opening-record',
        name: 'Registro de apertura del período',
        identifier: 'OpeningRecordList',
        path: '/apertura-periodo',
      },
      {
        permission: 'module-accounting-report',
        name: 'Reportes contables',
        identifier: 'AccoutingReportList',
        path: '/reportes-contables',
      },
      {
        // TODO: Revisar si el permission es el correcto
        permission: 'module-accounting-closure',
        name: 'Árbol de consolidación',
        identifier: 'ConsolidationTreeList',
        path: '/contabilidad/arbol-consolidacion',
      },
      {
        permission: 'module-accounting-schedule-deferrals',
        name: 'Programar diferidos',
        identifier: 'ScheduleDeferralList',
        path: '/contabilidad/programar-diferidos',
      },
      {
        permission: 'module-structures-types',
        name: 'Tipo de estructuras',
        identifier: 'StructureTypeList',
        path: '/tipo-estructuras',
      },
      {
        permission: 'module-voucher-authorization',
        name: 'Autorización de comprobantes',
        identifier: 'VoucherAuthorization',
        path: '/contabilidad/autorizacion-comprobantes',
      },
    ],
  },
  {
    key: 'SettlementCommissions',
    name: 'Liquidación de comisiones',
    icon: 'PencilLine',
    children: [
      {
        permission: 'module-portfolio-classification',
        name: 'Calificación de cartera',
        identifier: 'PortfolioClassificationList',
        path: '/liquidación-de-comisiones/calificaciones-de-cartera',
      },
      {
        permission: 'module-billing-trust',
        name: 'Definición inicial fideicomiso para facturación',
        identifier: 'BillingTrustList',
        path: '/liquidación-de-comisiones/fideicomisos-de-facturación',
      },
      {
        permission: 'module-third-party-billing',
        name: 'Definir terceros de facturación',
        identifier: 'ThirdPartyBillingList',
        path: '/liquidación-de-comisiones/terceros-de-facturación',
      },
    ],
  },
  {
    key: 'Budget',
    name: 'Presupuesto',
    icon: 'dollarSign',
    children: [
      {
        name: 'Rubros presupuestales',
        identifier: 'BudgetItemsList',
        path: '/presupuesto/rubros',
      },
      {
        name: 'Validaciones de cierre de vigencia',
        identifier: 'ClosureValidationsList',
        path: '/presupuesto/validaciones-cierre-vigencia',
      },
      {
        permission: 'module-movement-codes',
        name: 'Codigo Movimiento y Fuente Destino',
        identifier: 'BudgetMovementCodesList',
        path: '/presupuesto/codigos-movimientos',
      },
      {
        permission: 'module-operation-logs',
        name: 'Registro de Operaciones',
        identifier: 'BudgetOperationLogsList',
        path: '/presupuesto/registro-operaciones',
      },
      {
        permission: 'module-areas-responsibility',
        name: 'Areas de Responsabilidad',
        identifier: 'BudgetAreasResponsibilityList',
        path: '/presupuesto/areas-responsabilidad',
      },
      {
        name: 'Traslados presupuestales',
        identifier: 'BudgetTransferList',
        path: '/presupuesto/traslados-presupuestales',
      },
      {
        permission: 'module-budget-resources',
        name: 'Recursos presupuestales',
        identifier: 'ResourceBudgetList',
        path: '/presupuesto/recursos',
      },
      {
        //permission: 'module-cancellation-balances',
        name: 'Cancelación de Saldos',
        identifier: 'BudgetCancellationBalancesList',
        path: '/presupuesto/cancelacion-saldos',
      },
      {
        permission: 'module-budget-document-types',
        name: 'Tipos de documentos presupuestales',
        identifier: 'BudgetDocumentTypesList',
        path: '/presupuesto/tipos-de-documentos',
      },
      {
        permission: 'module-budget-accounting-mapping-parameters',
        name: 'Parámetros  homologación contabilidad vs presupuesto',
        identifier: 'BudgetAccountingHomologationParametersList',
        path: '/presupuesto/parametros-homologacion-presupuesto-contabilidad',
      },
      {
        permission: 'module-document-cancellation-list',
        name: 'Anulación de documentos presupuestales',
        identifier: 'BudgetDocumentCancellationList',
        path: '/presupuesto/anulacion-documentos-presupuestales',
      },
      {
        permission: 'module-budget-transfer-query',
        name: 'Consulta de traslados presupuestales',
        identifier: 'BudgetTransfersQueryList',
        path: '/presupuesto/consultas-traslados-presupuestales',
      },
      {
        name: 'Traslados presupuestales',
        identifier: 'BudgetTransferList',
        path: '/presupuesto/traslados-presupuestales',
      },
      {
        permission: 'module-budget-document-list',
        name: 'Consulta de documentos presupuestales',
        identifier: 'BudgetDocumentsList',
        path: '/presupuesto/consulta-documentos-presupuestales',
      },
    ],
  },
  {
    key: 'Audit',
    name: 'Auditoría',
    icon: 'FileSearch',
    children: [
      {
        name: 'Auditoria de ingreso a funcionalidades',
        identifier: 'AuditEntryOfFunctionalitiesList',
        path: '/auditoria/auditoria-ingreso-a-funcionalidades',
      },
      {
        name: 'Consultar log de bases de datos',
        identifier: 'AuditDatabaseLogsList',
        path: '/auditoria/log-base-de-datos',
      },
    ],
  },
  {
    key: 'BillingAndPortfolio',
    name: 'Facturación y cartera',
    icon: 'Wallet',
    children: [
      {
        permission: 'module-settlement-fiduciary-commissions',
        name: 'Autorización de comisiones fiduciarias',
        identifier: 'AuthorizationFiduciaryCommissionsList',
        path: '/facturacion-cartera/autorizacion-comisiones-fiduciarias',
      },
    ],
  },
  {
    key: 'Normative',
    name: 'Normativo',
    icon: 'Scale',
    children: [
      {
        permission: '',
        name: 'Parámetros equivalencias transmisiones',
        identifier: 'EquivalenceParametersList',
        path: '/normativo/parametros-equivalencias-transmisiones',
      },
    ],
  },
  {
    key: 'FixedAssets',
    name: 'Activos Fijos y Bienes',
    icon: 'Building',
    children: [
      {
        permission: 'module-fixed-assets',
        name: 'Configuración de activos fijos y bienes Activos fijos',
        identifier: 'ConfigurationTypesSubtypesList',
        path: '/activos-fijos/configuracion-tipos-activos-fijos-bienes',
      },
      {
        permission: 'module-fixed-assets',
        name: 'Registro y autorización de novedades',
        identifier: 'RegisterAuthorizationChangesList',
        path: '/activos-fijos/registro-autorizacion-novedades',
      },
    ],
  },
  {
    key: 'Seizures',
    name: 'Embargos',
    icon: 'FileText',
    children: [
      {
        permission: 'module-seizures',
        name: 'Embargos',
        identifier: 'SeizuresList',
        path: '/embargos',
        actions: [],
      },
    ],
  },
]
