import { INomenclature } from '@/interfaces/customs/AddressGenerator'
import { ValidationRule } from 'quasar'

export const commonNomenclatures: INomenclature[] = [
  {
    abbreviation: 'AP',
    name: 'Apartamento',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'AV', name: 'Avenida', requiresCustomName: true },
  { abbreviation: 'AUT', name: 'Autopista', requiresCustomName: true },
  {
    abbreviation: 'BRR',
    name: 'Barrio',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'CL', name: 'Calle', requiresCustomName: true },
  { abbreviation: 'CR', name: 'Carrera', requiresCustomName: true },
  { abbreviation: 'DG', name: 'Diagonal', requiresCustomName: false },
  {
    abbreviation: 'ED',
    name: 'Edificio',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'NORTE',
    name: 'Norte',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'SUR',
    name: 'Sur',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'TV', name: 'Transversal', requiresCustomName: false },
  {
    abbreviation: '#',
    name: '#',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: '-',
    name: '-',
    requiresCustomName: false,
    isMasculine: true,
  },
]

export const allNomenclatures: INomenclature[] = [
  { abbreviation: 'AC', name: 'Avenida Calle', requiresCustomName: false },
  { abbreviation: 'AD', name: 'Administración', requiresCustomName: true },
  { abbreviation: 'ADL', name: 'Adelante', requiresCustomName: false },
  {
    abbreviation: 'AER',
    name: 'Aeropuerto',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'AG', name: 'Agencia', requiresCustomName: true },
  { abbreviation: 'AGP', name: 'Agrupación', requiresCustomName: true },
  { abbreviation: 'AK', name: 'Avenida Carrera', requiresCustomName: false },
  {
    abbreviation: 'AL',
    name: 'Altillo',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'ALD', name: 'Al lado', requiresCustomName: false },
  {
    abbreviation: 'ALM',
    name: 'Almacén',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'AP',
    name: 'Apartamento',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'APTDO',
    name: 'Apartado',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'ATR',
    name: 'Atrás',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'AUT', name: 'Autopista', requiresCustomName: true },
  { abbreviation: 'AV', name: 'Avenida', requiresCustomName: true },
  {
    abbreviation: 'AVIAL',
    name: 'Anillo vial',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'BG', name: 'Bodega', requiresCustomName: true },
  {
    abbreviation: 'BL',
    name: 'Bloque',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'BLV',
    name: 'Boulevard',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'BRR',
    name: 'Barrio',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'C',
    name: 'Corregimiento',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'CA', name: 'Casa', requiresCustomName: false },
  {
    abbreviation: 'CAS',
    name: 'Caserío',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'CC',
    name: 'Centro comercial',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'CD', name: 'Ciudadela', requiresCustomName: true },
  { abbreviation: 'CEL', name: 'Célula', requiresCustomName: true },
  {
    abbreviation: 'CEN',
    name: 'Centro',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'CIR', name: 'Circular', requiresCustomName: false },
  { abbreviation: 'CL', name: 'Calle', requiresCustomName: true },
  {
    abbreviation: 'CLJ',
    name: 'Callejón',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'CN',
    name: 'Camino',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'CON',
    name: 'Conjunto residencial',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'CONJ',
    name: 'Conjunto',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'CR', name: 'Carrera', requiresCustomName: true },
  { abbreviation: 'CRT', name: 'Carretera', requiresCustomName: false },
  { abbreviation: 'CRV', name: 'Circunvalar', requiresCustomName: false },
  {
    abbreviation: 'CS',
    name: 'Consultorio',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'DG', name: 'Diagonal', requiresCustomName: false },
  {
    abbreviation: 'DP',
    name: 'Depósito',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'DPTO',
    name: 'Departamento',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'DS',
    name: 'Depósito sótano',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'ED',
    name: 'Edificio',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'EN', name: 'Entrada', requiresCustomName: false },
  { abbreviation: 'ES', name: 'Escalera', requiresCustomName: false },
  { abbreviation: 'ESQ', name: 'Esquina', requiresCustomName: false },
  {
    abbreviation: 'ESTE',
    name: 'Este',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'ET', name: 'Etapa', requiresCustomName: false },
  {
    abbreviation: 'EX',
    name: 'Exterior',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'FCA', name: 'Finca', requiresCustomName: true },
  {
    abbreviation: 'GJ',
    name: 'Garaje',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'GS',
    name: 'Garaje sótano',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'GT', name: 'Glorieta', requiresCustomName: false },
  { abbreviation: 'HC', name: 'Hacienda', requiresCustomName: true },
  {
    abbreviation: 'HG',
    name: 'Hangar',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'IN',
    name: 'Interior',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'IP',
    name: 'Inspección de Policía',
    requiresCustomName: true,
  },
  {
    abbreviation: 'IPD',
    name: 'Inspección Departamental',
    requiresCustomName: true,
  },
  {
    abbreviation: 'IPM',
    name: 'Inspección Municipal',
    requiresCustomName: true,
  },
  {
    abbreviation: 'KM',
    name: 'Kilómetro',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'LC',
    name: 'Local',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'LM',
    name: 'Local mezzanine',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'LT',
    name: 'Lote',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'MD',
    name: 'Módulo',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'MJ',
    name: 'Mojón',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'MLL',
    name: 'Muelle',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'MN',
    name: 'Mezzanine',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'MZ', name: 'Manzana', requiresCustomName: false },
  {
    abbreviation: 'NOMBRE VIA',
    name: 'Vías de nombre común',
    requiresCustomName: true,
  },
  {
    abbreviation: 'NORTE',
    name: 'Norte',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'O',
    name: 'Oriente',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'OCC',
    name: 'Occidente',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'OESTE',
    name: 'Oeste',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'OF', name: 'Oficina', requiresCustomName: true },
  {
    abbreviation: 'P',
    name: 'Piso',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'PA', name: 'Parcela', requiresCustomName: false },
  {
    abbreviation: 'PAR',
    name: 'Parque',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'PD',
    name: 'Predio',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'PH',
    name: 'Penthouse',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'PJ',
    name: 'Pasaje',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'PL', name: 'Planta', requiresCustomName: false },
  {
    abbreviation: 'PN',
    name: 'Puente',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'POR', name: 'Portería', requiresCustomName: false },
  {
    abbreviation: 'POS',
    name: 'Poste',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'PQ',
    name: 'Parqueadero',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'PRJ',
    name: 'Paraje',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'PS',
    name: 'Paseo',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'PT',
    name: 'Puesto',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'PW',
    name: 'Park Way',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'RP',
    name: 'Round Point',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'SA',
    name: 'Salón',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'SC',
    name: 'Salón comunal',
    requiresCustomName: true,
    isMasculine: true,
  },
  { abbreviation: 'SD', name: 'Salida', requiresCustomName: false },
  {
    abbreviation: 'SEC',
    name: 'Sector',
    requiresCustomName: true,
    isMasculine: true,
  },
  {
    abbreviation: 'SL',
    name: 'Solar',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'SM', name: 'Súper manzana', requiresCustomName: false },
  {
    abbreviation: 'SS',
    name: 'Semisótano',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: 'ST',
    name: 'Sótano',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'SUITE', name: 'Suite', requiresCustomName: true },
  {
    abbreviation: 'SUR',
    name: 'Sur',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'TER', name: 'Terminal', requiresCustomName: true },
  {
    abbreviation: 'TERPLN',
    name: 'Terraplén',
    requiresCustomName: false,
    isMasculine: true,
  },
  { abbreviation: 'TO', name: 'Torre', requiresCustomName: true },
  { abbreviation: 'TV', name: 'Transversal', requiresCustomName: false },
  { abbreviation: 'TZ', name: 'Terraza', requiresCustomName: true },
  { abbreviation: 'UN', name: 'Unidad', requiresCustomName: true },
  { abbreviation: 'UR', name: 'Unidad residencial', requiresCustomName: true },
  { abbreviation: 'URB', name: 'Urbanización', requiresCustomName: true },
  { abbreviation: 'VRD', name: 'Vereda', requiresCustomName: true },
  { abbreviation: 'VTE', name: 'Variante', requiresCustomName: true },
  { abbreviation: 'ZF', name: 'Zona franca', requiresCustomName: false },
  { abbreviation: 'ZN', name: 'Zona', requiresCustomName: true },
  {
    abbreviation: '#',
    name: '#',
    requiresCustomName: false,
    isMasculine: true,
  },
  {
    abbreviation: '-',
    name: '-',
    requiresCustomName: false,
    isMasculine: true,
  },
]

export const digits = Array.from({ length: 10 }, (_, i) => String(i))

export const letters = [
  ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)),
  'BIS',
]

// Reglas obligatorias
export const inputRulesRequired: ValidationRule[] = [
  (val: string | null) => !val || val.length <= 150 || 'Máximo 150 caracteres',
]
